# Generated by Django 4.1.1 on 2022-10-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dump_files',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=100000)),
                ('textarea', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='log_files',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=100000)),
                ('textarea', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='proc_files',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=100000)),
                ('textarea', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
    ]
