# Generated by Django 4.1.1 on 2022-10-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dump_files_log_files_proc_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
