# Generated by Django 4.1.1 on 2022-10-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
    ]
